version: 2
jobs:
  build:
 test_cypress:
    working_directory: ~/theintercept
    docker:
      - image: cypress/base:6
        environment:
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          name: Restoring cached yarn dependencies
          keys:
            - integration-tests-yarn-dependencies-{{ checksum "integration-tests/yarn.lock" }}
      - run:
          name: Installing dependencies with yarn
          command: |
            cd integration-tests
            yarn install --frozen-lockfile
            yarn list
      - save_cache:
          name: Caching yarn dependencies
          key: integration-tests-yarn-dependencies-{{ checksum "integration-tests/yarn.lock" }}
          paths:
            - ~/.cache/Cypress
            - ~/.cache/yarn
            - ~/theintercept/integration-tests/node_modules
      - run:
          name: Running E2E tests with JUnit reporter
          command: |
            cd integration-tests
            yarn test:record
      - store_test_results:
          path: integration-tests/test-results
      - store_artifacts:
          path: integration-tests/test-results
      - store_artifacts:
          path: integration-tests/test-artifacts
